latency-wait: "60"
jobscript: "lsf-jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "False"
restart-times: "0"
jobs: "500"
cluster: "lsf-submit.py"
cluster-status: "lsf-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"